spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quality
    continue-on-error: false
    username: dq
    password: dq123456
  jpa:
    properties:
      hibernate.hbm2ddl.auto: update
  profiles:
    active: dev
