FROM alpine:3.9
label maintainer='qkits@gmail.com'
RUN apk add --no-cache openjdk8
COPY files/UnlimitedJCEPolicyJDK8/* \
  /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/
COPY src/target/*.jar /opt/app

## todo: